"""holidays and special days

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 12:55:13.021404
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "special_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "day"),
    )
    with op.batch_alter_table("special_days", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_special_days_team_id"), ["team_id"], unique=False)

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("holiday_country", sa.String(length=8), server_default="", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "holiday_subdivision", sa.String(length=16), server_default="", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_column("holiday_subdivision")
        batch_op.drop_column("holiday_country")

    with op.batch_alter_table("special_days", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_special_days_team_id"))

    op.drop_table("special_days")
    # ### end Alembic commands ###
